################
# Dataset
################
total_jobs: 100
batch_task_path: "E:/Workshop/real-time-faas/dataset/batch_task.csv"
selected_batch_task_path: "E:/Workshop/real-time-faas/dataset/selected_batch_task.csv"
batch_task_topological_order_path: "E:/Workshop/real-time-faas/dataset/batch_task_topological_order.csv"
batch_instance_path: "E:/Workshop/real-time-faas/dataset/batch_instance.csv"
selected_batch_instance_path: "E:/Workshop/real-time-faas/dataset/selected_batch_instance.csv"
batch_instance_topological_order_path: "E:/Workshop/real-time-faas/dataset/batch_instance_topological_order.csv"

################
# Scheduler
################
# edge computing environment settings
cpu_nums: 3  # 100 memory error
n_pairs: 12

# density is used to adjust the connectivity of the graph
density: 10  # 100 will get memory error

# bandwidth generation scope
bw_lower: 30
bw_upper: 70

# processing power scope
pp_lower: 7
pp_upper: 14

# job settings (processing power required by each task, the data stream size of each link)
pp_required_lower: 1
pp_required_upper: 2
data_stream_size_lower: 1
data_stream_size_upper: 10
max_task_nums: 250
max_value: 9e+4

################
# Autoscaler
################
total_machines: 100
container_usage_path: "E:/Workshop/real-time-faas/dataset/container_usage.csv"
selected_container_usage_path: "E:/Workshop/real-time-faas/dataset/selected_container_usage.csv"
